version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017

  mysql:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3307:3306

  mariadb:
    image: mariadb:10.6.14
    environment:
      - MARIADB_ROOT_PASSWORD=4321
    ports:
      - 3308:3306

  my_express:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:4000
    environment:
      - MONGODB_HOST=mongodb

      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234

      - MARIADB_HOST=mariadb
      - MARIADB_USER=root
      - MARIADB_PASSWORD=4321
    volumes:
      - ./server:/servidor
      - /servidor/node_modules
